### ISSUE TITLE
Questions about learnable parameters size and speed of model

### ISSUE THREAD

**Issue by magrenimish** [facebookresearch/frankmocap#111]
Hi
Would you be able to tell me the number of overall learnable parameters for the Copy-and-Paste as well as the Optimization based integration methods?
Also, I'm not sure why the offline CP model performs slower than the online CP model?
Thanks

**Comment by penincillin** [comment]
For copy-and-paste and optimization, we introduce no additional learnable parameters.
The reason why optimization is must slower is that it requires iterations to progressively adjust the parameters while copy-and-paste can directly produces the final results (i.e. whole-body motion) from body-only and hand-only predictions.

**Comment by magrenimish** [comment]
I understand why optimization based method is slower but I'm not sure why the Online CP performance is slower than the Offline CP performance
I'm referring to columns 4 and 5 of Table 1

**Comment by penincillin** [comment]
@magrenimish 
In table 1, running speed of Online (CP) is 9.5 fps while the speed of Offline (CP) is 4.5 fps. Therefore, Online CP performance is faster than Offline CP performance. 
The unit is actually speed instead of running time, therefore the higher the faster. We apologize for the confusing usage of the unit. We will modify this part in our later version.
