### ISSUE TITLE
freeglut (foo): failed to open display ''

### ISSUE THREAD

**Issue by cloudweather** [facebookresearch/frankmocap#12]
Hi, thank you guys for your wonderful work. 
I am just wondering how I can get this working in Windows WSL2 because I am stuck here with this line of error:
```
freeglut (foo): failed to open display ''
```
Is there any way that I can get around this? Thank you.

**Comment by jhugestar** [comment]
That's because opengl viewer requires a screen to display the output, which I presume you don't have in the system. 

Can you try the command with 'xvfb-run -a' which is a way to bypass that requirement?

xvfb-run -a python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output

Otherwise, you can try other renderer, pytorch3d or opendr, which do not have such requirement.

**Comment by cloudweather** [comment]
Using that command works. Thank you.

**Comment by monacv** [comment]
@jhugestar the command doesn't work for me unfortunately in CentOS 7.
```
 $ xvfb-run -a python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_outp 
Loading Body Pose Estimator
Loading Third View Hand Detector
freeglut (foo): OpenGL GLX extension not supported by display ':99'
```

**Comment by Shreeshail-Hingane** [comment]
> That's because opengl viewer requires a screen to display the output, which I presume you don't have in the system.
> 
> Can you try the command with 'xvfb-run -a' which is a way to bypass that requirement?
> 
> xvfb-run -a python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
> 
> Otherwise, you can try other renderer, pytorch3d or opendr, which do not have such requirement.

Using 'xvfb-run -a' before the python command did bypass the requirement, but I don't see the output. What should I do to see the OpenGL output? I am running the command on a VM, so I guess it doesn't have a screen by default.

**Comment by CARASO** [comment]
export DISPLAY=:0.0
