### ISSUE TITLE
problems about perspective projection

### ISSUE THREAD

**Issue by biansy000** [facebookresearch/frankmocap#141]
I find it a little confused to understand the projecting methods used in the code. Especially, I cannot understand  `convert_smpl_to_bbox` and `convert_bbox_to_oriIm` functions in copy_and_test.py. It seems that you are not using conventional perspective projection (as used in SPIN model), and the z-axis coordinate is not used in projection procedure. The use of `resnet_input_size_half` is also strange

Could you please explain briefly about how your projection method works?

**Comment by penincillin** [comment]
@biansy000 
We use orthogonal projection for both body and hand, which directly taking the x, y coords and neglects the z coords.
SPIN also uses orthogonal projection instead of perspective projection. This practice (using orthogonal projection) can be traced back to HMR. The reason is that we assume the agnostic of camera intrinsics, which cannot be faithfully estimated from in-the-wild images. Therefore, we ease the problem and choose to use orthogonal projection.

**Comment by biansy000** [comment]
Thanks! I understand the code now. 
BTW, I think that SPIN and HMR at least in some part of the code do use perspective projection ([https://github.com/nkolot/SPIN/blob/master/utils/geometry.py](url)) :joy:. That is why my confusion arises.
