### ISSUE TITLE
Get the head bbox coordinates from the SMPL-X predicted vertices

### ISSUE THREAD

**Issue by oscarlorente** [facebookresearch/frankmocap#152]
Hello,
I'm using frankmocap to get the SMPL-X model of a man, but I also need to detect his head using the corresponding SMPL-X prediction. So far, I've been able to identify the vertices corresponding to the head (using the SMPL-X - FLAME correspondences from [here](https://smpl-x.is.tue.mpg.de/download.php)) and plot it using your openGL renderer:

![Screenshot from 2021-08-23 14-35-56](https://user-images.githubusercontent.com/42140425/130448093-c6d62d6e-8aff-4432-8a58-c3ded4b42917.png)

However, I'm interested in getting the head's bbox coordinates, that is, knowing the pixels on which the SMPL-X vertices are projected. I'm not sure how to get them from the renderer code, any ideas?

**Comment by penincillin** [comment]
Basically, you need to project the head vertices to image space and obtain head bbox from the projected 2D head vertices.
You can check the [code here](https://github.com/facebookresearch/frankmocap/blob/c43dcb89690f57a79fe757e3e2bdebe7e690bf86/bodymocap/body_mocap_api.py#L94), where ```pred_vertices_img``` is already aligned to the image space. You can directly take the ```[x, y]``` coordinates to obtain the projected 2D vertices. Since you already know how to select out head vertices, you just need to do that again to ```pred_vertices_img``` to obtain the head vertices in image space and then obtain 2D head bbox.

**Comment by oscarlorente** [comment]
That works like a charm, thank you very much!

**Comment by ruyiwei-cas** [comment]
@oscarlorente

**Comment by ruyiwei-cas** [comment]
@oscarlorente 
How did you get this picture and how to paste the RGB information into the generated mesh.
![image](https://user-images.githubusercontent.com/14344027/142579014-2b6bc04d-8cfb-49f3-b08c-fef86370493a.png)
