### ISSUE TITLE
Output format and rescaling

### ISSUE THREAD

**Issue by tfederico** [facebookresearch/frankmocap#154]
Hello,

in the documentation you say that when prediction 3d coordinates, the X and Y are "aligned to input image".
Could you please explain this in detail? Does it mean that the model outputs something in the range [-1, 1] or [0, 1] and you rescale it based on the image size?

If I wanted to rescale them in the range [-1, 1], should I just divide them by the image width and height respectively? Or do you perform a square cropping (e.g., 256x256) and one should divide the output accordingly?

Also, does [0, 0] correspond to the top left corner of the image?

**Comment by tfederico** [comment]
Also how do you rescale the Z component?

**Comment by penincillin** [comment]
The original predictions from SMPL/MANO/SMPL-X use meter as the unit, let say it is ```p0```. We first scale these predictions to input image space, using estimated weak perspective camera parameters. Since the input images are cropped from the original images, we further rescale the predictions from cropped image space to original image space.

**Comment by tfederico** [comment]
How is the cropping perfomed? Do you crop a N by N pixels square around the center of the bounding box?
