### ISSUE TITLE
Internal Error with openGL?

### ISSUE THREAD

**Issue by sunnyCST** [facebookresearch/frankmocap#192]
Hi, thanks for the fantastic work!

I was trying to follow the install instruction of body motion capture, but met this error:

(frankmocap) sunyn@zkyd:/data/sunyn/3DBodyRecon/frankmocap$ xvfb-run -a python -m demo.demo_bodymocap --input_path ./sample_data/han_short.mp4 --out_dir ./data/output/
Loading Body Pose Estimator
use_smplx False
freeglut (foo):  ERROR:  Internal error <FBConfig with necessary capabilities not found> in function fgOpenWindow

The code runs on Ubuntu16.04, python3.7, cuda10.1, torch1.6.0.

Could you help me fix the bug? Thanks a lot!

p.s. If any additional information is needed, just ask me and I'll reply as soon as possible :-)

**Comment by penincillin** [comment]
@sunnyCST 
Sorry for the delayed reply. The error is caused by running code on the remote server without display. You can choose other rendering methods such as Pytorch3D or OpenDR. You can refer to this [link](https://github.com/facebookresearch/frankmocap/blob/main/docs/run_totalmocap.md#a-quick-start).

**Comment by sunnyCST** [comment]
Thanks for your reply! The problem is fixed by adding `--renderer_type pytorch3d`.
