### ISSUE TITLE
ImportError: cannot import name '_C' from 'model'

### ISSUE THREAD

**Issue by trilokpadhi** [facebookresearch/frankmocap#5]
Hi 
Thanks for the amazing repo and also for easy to understand step by step installation . I have followed all the installation steps in order from here `https://github.com/facebookresearch/frankmocap/blob/master/docs/INSTALL.md#installing-all-modules` .

But I am getting an error when I run     `python -m demo.demo_frankmocap --input_path ./sample_data/single_totalbody.mp4 --out_dir ./mocap_output` 

I am stuck in the error and here is the traceback.

`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/trilok/Desktop/MOTION TRACKING/frankmocap/demo/demo_frankmocap.py", line 23, in <module>
    from handmocap.hand_bbox_detector import HandBboxDetector
  File "/home/trilok/Desktop/MOTION TRACKING/frankmocap/handmocap/hand_bbox_detector.py", line 33, in <module>
    from detectors.hand_object_detector.lib.model.roi_layers import nms # might raise segmentation fault at the end of program
  File "/home/trilok/Desktop/MOTION TRACKING/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/home/trilok/Desktop/MOTION TRACKING/frankmocap/detectors/hand_object_detector/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: cannot import name '_C' from 'model' (/home/trilok/Desktop/MOTION TRACKING/frankmocap/model/__init__.py)
`

Also the file` _init_.py` in the model folder is empty . 
Can you please tell how to fix this issue ?

Thanks
Trilok

**Comment by jhugestar** [comment]
Hi Trilok,

Can you double check whether you installed detectron2 correctly before running our installation script? I believe the `model` is not ours, but hand_object_detector's module (based on detectron2).

**Comment by penincillin** [comment]
@trilokpadhi 
Hi Trilok,

Can you also check whether you have successfully compiled hand_detectors: https://github.com/facebookresearch/frankmocap/blob/a33f2f59d2e8d349c2e38e3ea93015763ec61f8a/scripts/install_hand_detectors.sh#L14

**Comment by trilokpadhi** [comment]
Hi Yu @penincillin and  Han @jhugestar 
Thank you so much for your prompt replies . It worked for me when I build the detectron from source and not with the pre-built binary, as it faced issue with cuda version as it wasnt able to find the cublas_v2.h file. Finally it worked for me with cuda version 10.2 .

**Comment by lan786** [comment]
Hi @trilokpadhi  Can you tell me about your system configuration? For this [hand object detector](https://github.com/ddshan/hand_object_detector) which version of torch and cuda you used? 
In my case I'm facing problem. As in this repo torch 1.6 and cuda 10.1 is suggested but with this configuration I'm unable to compile [hand object detector](https://github.com/ddshan/hand_object_detector), detectron2 is working. 
By reading [hand object detector](https://github.com/ddshan/hand_object_detector) installation instruction I install torch 1.0.1.post2 with cudatoolkit_10.0 and hand object detector compiled successfully. 
With torch 1.0.1.post2 body_mocap part is working but still I'm facing problem in hand_mocap part due to torch version. 
I wanna ask that how did you compile [hand object detector](https://github.com/ddshan/hand_object_detector) ? Thanks

**Comment by woo1** [comment]
> @trilokpadhi
> Hi Trilok,
> 
> Can you also check whether you have successfully compiled hand_detectors:
> 
> https://github.com/facebookresearch/frankmocap/blob/a33f2f59d2e8d349c2e38e3ea93015763ec61f8a/scripts/install_hand_detectors.sh#L14

I fixed this error after upgrading my cuda version from 10.1 to 10.2 and install cudnn 8.2.0.
And check "CUDA_HOME" or "CUDA_PATH" variable in "~/.bashrc"
