### ISSUE TITLE
How to rescale 3D keypoint annotations?

### ISSUE THREAD

**Issue by VVingerfly** [facebookresearch/frankmocap#68]
Thanks for the excellent work!

I was wondering how you perform dataset preprocessing on the 3D hand joints, the paper says "Rescaling all 3D keypoint annotations to be compatible with our hand model, by using the middle finger’s knuckle length as a reference."
Does this mean to scale 3D joints by keeping the length of the middle finger’s knuckle the same for all the 3D joints in the training dataset?

Thanks a lot!
B. R.

**Comment by penincillin** [comment]
@VVingerfly 
That's what we do in experiments. But a better way might be to stat the overall scale difference between SMPL-X joints and the target dataset, while still using middle finger's knuckle length as a reference.
For example, say the average length of SMPL-X's middle finger knuckle is 1 and your target dataset is 1000. Then you can apply the scale factor 1 / 1000 to all the joints of your target dataset.

**Comment by VVingerfly** [comment]
Hi, @penincillin 

Thanks for your kindly reply. I have a few more questions.

1. What's the proportion of the different hand training dataset? i.e., the ratio of FreiHand and HO3D dataset when use them for training, and the ratio of each dataset (FreiHAND, HO-3D, MTC, STB & RHD) when use all of them for training. Does different proportions affect the final results a lot?

2. Did you perform any other data augmentations except for those (i.e., random scaling, translation, rotation, color jittering, and synthetic motion blur) mentioned in the paper? for example, background augmentation for FreiHand dataset (since most of the background is green).

3. Did you clean the datasets before using them for training? I saw many bad annotations in these dataset, especially in HO3D. Do these flaw datas have any influence on the final performance?

Sorry for the too many questions! Looking forward to your reply.

Thanks a lot! :)

B. R.

**Comment by penincillin** [comment]
@VVingerfly 

1. During training, we didn't explicitly set proportion to each dataset (such as SPIN), instead, I set a bound (which is 50,00) for number of samples of each dataset used in training. For dataset with less than 50,000 samples, I use all the samples. For other datasets, I randomly select 50,000 samples each epoch.
2. Random scaling, translation, rotation, color jittering, and synthetic motion blur are all the data augmentation I performed. As for background augmentation, FreiHand itself provides images with background augmentation. These images are also used in training. Besides, no background augmentation is applied to other datasets.
3. I didn't clean HO-3D.  But I cleaned MTC since many hands with annotations are actually occluded. To clean MTC, you need a rough fitting of body using mesh models such as Adam or SMPL-X. Then use the occlusion relationship to filter out occluded hands.

**Comment by VVingerfly** [comment]
Hi, @penincillin 

Thank you very much for the patient and helpful reply! 
I am closing this issue now!

B.R.
