### ISSUE TITLE
smpl parameters

### ISSUE THREAD

**Issue by melih1996** [facebookresearch/frankmocap#70]
Hi, how to get smpl parameters that are beta and pose params from an image?

**Comment by penincillin** [comment]
```python -m demo.demo_bodymocap --input_path directory_of_your_image --out_dir ./mocap_output --renderer_type pytorch3d```
Our code supports image input. You can run on your images by setting ```input_path``` to the directory of your images.

**Comment by melih1996** [comment]
I want to use the smpl parameters for another project but when I use it the body model transforms to upside down. Are the beta parameters from smplx or smpl? If smplx then how to convert it to smpl parameters?

**Comment by penincillin** [comment]
@melih1996 
Sorry for the delayed reply. 
For bodymocap, SMPL is used by default to represent 3D body. To use SMPL-X for 3D body, you can set ```--use_smplx```.
As for the problem of upside down, it should have no relation with the choice of SMPL or SMPL-X, I guess it's due to the different definition of coordinate system between the renderer you use and SMPL / SMPL-X. For SMPL / SMPL-X, the coordinate system is the same as image coordinate system, where x-axis increases from left to right and y-axis increases from up to down.

**Comment by akchain** [comment]
Hello, is it possible to get smpl parameters that are beta and pose params from a .obj file? Thanks.
