### ISSUE TITLE
Batch size

### ISSUE THREAD

**Issue by piksang** [facebookresearch/frankmocap#72]
Thanks for your excellent work. Can you tell me the batch size you use for your hand motion capture training?

**Comment by penincillin** [comment]
@piksang 
In our experiment, the batch_size is set to be 256 (distributed training on 4 GPUs, the batch_size on each GPU is 64).
According to my experience, batch_size has negligible influence on the performance, so you don't have to insist on this number :)

**Comment by piksang** [comment]
Thanks for you reply, my experiments have showed the same result.

**Comment by piksang** [comment]
I have another question. For each dataset, does the length between the finger nodes need to be the same as that of the template in smplx.

**Comment by penincillin** [comment]
@piksang 
This problem is a little tricky. In general, you should make the unit of annotated 3D joints be the same as SMPL-X hand template. There is no requirement to make the finger length exactly the same.  To be more specific, the unit of SMPL-X's finger length is meter, if some datasets use millimetre as the unit, you should multiple its joints annotations by ```1e-3```
