### ISSUE TITLE
About 3D loss

### ISSUE THREAD

**Issue by YuyanHuang** [facebookresearch/frankmocap#82]
For 3D loss, I learned that GT 3D is the coordinate point of camera space. 
1. May I ask whether the unit of coordinate point you use is meter or millimeter?
2. Calculate 2D loss and 3D loss at the same time, is the proportion of depth information learning not high enough?

**Comment by penincillin** [comment]
@YuyanHuang 
1. The unit of coordinate is meter.
2. Sorry, I didn't quite get you. Does you mean the influence of loss weights between 2D and 3D Loss ?

**Comment by YuyanHuang** [comment]
@penincillin 
For data sets with GT 3D, such as FreiHand, the loss of X and Y is calculated twice, and its proportion in the total LOSS will be higher than Z.

**Comment by YuyanHuang** [comment]
@penincillin 
Sorry, I may have more questions, because it is not certain how GT 3D is processed before the 3D loss calculation. The way I know is to unify the unit to meters, re-adjust the order of the joint points and subtract index1. 

However, I don’t know if there is a rescale operation. 
1. Because the output of SMPLX is between [-1,1]. 
2. In addition, I saw that when `SMPL 3D coord`was converted to `2D bbox`, the depth information was rescaled. Why does it need to be rescaled here, and what is the output unit?

**Comment by penincillin** [comment]
@YuyanHuang 
1. The output of SMPLX is between [-1, 1] and the unit is meter. Therefore, we rescale the unit of GT 3D joints to meter. Besides, in calculating losses, GT 3D joints and predicted 3D joints from SMPL-X are translated to the same root, for example, using wrist as the root.
2. We rescale the depth information here because we want the rescaled 3D vertices still have valid shape. It's hard to say the output unit. You can view it as in pixel space.

**Comment by YuyanHuang** [comment]
@penincillin 
Thanks!!!
