### ISSUE TITLE
freeglut (foo): OpenGL GLX extension not supported by display ':99'

### ISSUE THREAD

**Issue by monacv** [facebookresearch/frankmocap#93]
When I am trying to run this command on the server, I get this error. I was wondering if you might be able to help me by any chance?

```
[jalal@goku frankmocap]$ xvfb-run -a python -m demo.demo_frankmocap --input_path ./sample_data/han_short.mp4 --out_dir ./mocap_output
Loading Body Pose Estimator
Loading Third View Hand Detector
freeglut (foo): OpenGL GLX extension not supported by display ':99'
```

I have CentOS 7:

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core
```
I have two NVIDIA 1080 GPUs:
![Screenshot from 2021-04-15 16-17-30](https://user-images.githubusercontent.com/76495162/114932967-243e7f00-9e06-11eb-84a4-4c3865ecc36c.png)

also,
```
$ glxinfo
Error: unable to open display 
```

**Comment by penincillin** [comment]
@monacv 
This error is related to OpenGL. In general, it's hard to use OpenGL on a server due to the screen issue.
To render the predicted results, you can choose to use Pytorch3D or OpenDR. Please refer to [here](https://github.com/facebookresearch/frankmocap/blob/master/docs/run_bodymocap.md#other-renderer-options) for more details.
